### ISSUE TITLE
thread-supervisor.cabal was modified manually, please use --force to overwrite.

### ISSUE THREAD

**Issue by o1lo01ol1o** [nshimaza/async-supervisor#1]
Hi, 
  Providing both a cabal file and package.yaml causes nix's `callCabal2nix` to balk as we cannot currently pass `--force` to hpack, only to cabal.  As a work around, one can mutate the source first, but that's not super friendly.

**Comment by nshimaza** [comment]
Thank you for reporting!
I believe I never edit thread-supervisor.cabal by hand but I double checked.  Then, I confirmed thread-supervisor.cabal generated by my hpack 0.34.2 is identical to what on the repo.
I hope I can help you but unfortunately I don't find resolution from this repo.

**Comment by nshimaza** [comment]
Close due to no response in a month.
